---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 14:28
---
local Enum = {}

Enum.LayerType = {
    Buttom = 1,
    UI = 2,
    Tip = 3,
    Mask = 4,
}

return Enum