---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 14:28
---
local Enum = {}

local LayerType = {
    Buttom = 1,
    UI = 2,
    Tip = 3,
    Mask = 4,
}

local ReturnKeyOperation = {
    Back = 1,
}

local WinCfg = {
    demo = {luaPath = "FrameWork/UI/Window.lua", prefabPath = "Assets/GameData/UI/prefabs/SportToolPanel.prefab"},
}

local ViewCacheType = {
    Root = 1,
    This = 2,
}

Enum.LayerType = LayerType
Enum.ReturnKeyOperation = ReturnKeyOperation
Enum.WinCfg = WinCfg
Enum.ViewCacheType = ViewCacheType
return Enum