---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 14:28
---
local Enum = {}

local LayerType = {
    Buttom = 1,
    UI = 2,
    Tip = 3,
    Mask = 4,
}

local ReturnKeyOperation = {
    Back = 1,
}

local WindowCfg = {
    demo = {name = "demo", layerType = LayerType.UI, returnKeyOperation = ReturnKeyOperation.Back, uiCfg = nil},
}

Enum.LayerType = LayerType
Enum.ReturnKeyOperation = ReturnKeyOperation
Enum.WindowCfg = WindowCfg
return Enum