---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 12:04
---

-- 枚举
Enum = require("FrameWork/Init/Enum.lua")

-- 类工具
class = require("FrameWork/Utility/ClassUtil.lua")
Class = class

-- 日志工具
log = require("FrameWork/Utility/LogUtil.lua")

-- 函数工具
local funcUtil = require("FrameWork/Utility/FunctionUtil.lua")
WrapPartial1 = funcUtil.WrapPartial1
WrapPartial2 = funcUtil.WrapPartial2

-- C#导出类
GameManager = CS.GameManager.Instance
CallManager = GameManager.m_CallMgr

-- C#导出类
GameObject = CS.UnityEngine.GameObject