---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/2 0:11
---

local v = {
    [1]={id=1, name="物品1"},
    [2]={id=2, name="物品2"},
    [3]={id=3, name="物品3"},
}

return v