---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 12:32
---

local Partial1 = function(paramFunc, param1)
    local func = function(...)
        return paramFunc(param1, ...)
    end
    return func
end

local Partial2 = function(paramFunc, param1, param2)
    local func = function(...)
        return paramFunc(param1, param2, ...)
    end
    return func
end

return {
    WrapPartial1 = Partial1,
    WrapPartial2 = Partial2,
}