---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 12:23
---

local logIdx = 1
log = function(str)
	str = string.format("LuaLog%d：%s", logIdx, str)
	CS.UnityEngine.Debug.Log(str)
	logIdx = logIdx + 1
end

return log
