---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 14:02
---

local Window = require("FrameWork/UI/Window.lua")
local UIManager = class("UIManager")

function UIManager:ctor()
    self.uiRoot = nil
    self.buttomLayer = nil
    self.uiLayer = nil
    self.tipLayer = nil
    self.maskLayer = nil
    self.enumToLayer = nil
end

function UIManager:Init()
    self.uiRoot = GameManager.gameObject.transform:Find("UIRoot")
    self.buttomLayer = self.uiRoot:Find("ButtomLayer")
    self.uiLayer = self.uiRoot:Find("UILayer")
    self.tipLayer = self.uiRoot:Find("TipLayer")
    self.maskLayer = self.uiRoot:Find("MaskLayer")
    self.enumToLayer = {
        [Enum.LayerType.Buttom] = self.buttomLayer,
        [Enum.LayerType.UI] = self.uiLayer,
        [Enum.LayerType.Tip] = self.tipLayer,
        [Enum.LayerType.Mask] = self.maskLayer,
    }
end

function UIManager:GetLayerByType(type)
    return self.enumToLayer[type]
end

function UIManager:Destroy()
    self.uiRoot = nil
    self.buttomLayer = nil
    self.uiLayer = nil
    self.tipLayer = nil
    self.maskLayer = nil
    self.enumToLayer = nil
end

function UIManager:CreateWindow(winCfg)
    local windowClass = require(winCfg.luaPath)
    local destroyFunc = function(w)
        GameObject.Destroy(w.gameObject)
    end
    local win = windowClass.New(self.uiRoot, destroyFunc)
    local cache = win:GetChache()
    local layerType = win:GetLayerType()
    local layerTrans = self:GetLayerByType(layerType)
    local assetItem = cache:Load(winCfg.prefabPath)
    local trans = GameObject.Instantiate(assetItem.GameObject, layerTrans).transform
    win.transform = trans
    win.gameObject = trans.gameObject
    win.gameObject.name = win:GetName()
    win:Init()
    return win
end

return UIManager