---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 15:17
---
local Widget = require("FrameWork/UI/Widget.lua")
local Window = class("Window", Widget)

function Window:ctor(path, layerTrans)
    self.super.ctor(self, layerTrans)

    local mainWidget = self:CreateUIByPath(path)
    local cache = self:GetChache()
    mainWidget:SetExternalCache(cache)

    self.mainWidget = mainWidget
    self.transform = mainWidget.transform
    self.gameObject = mainWidget.gameObject
    self.CreateUIByPath = function(this, path1, widgetClass)
        return this.mainWidget:CreateUIByPath(path1, widgetClass)
    end
    self.CreateUI = function(this, trans, widgetClass)
        return this.mainWidget:CreateUI(trans, widgetClass)
    end
    self:Init()
end

-- 新增接口，关闭自身
function Window:Close()
    self:Destroy()
    GameObject.Destroy(self.gameObject);
end

return Window