---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qqqqq.
--- DateTime: 2020/5/17 15:17
---
local View = require("FrameWork/UI/View.lua")
local Window = class("Window", View)

Window.uiCfg = nil

function Window:ctor(trans, destroyCall)
    Window.super.ctor(self, trans)
    self.destroyCall = destroyCall
end

function Window:Destroy()
    Window.super.Destroy(self)
    if self.destroyCall then self.destroyCall(self) end
end

function Window:GetName()
    return self:_OnGetName()
end

function Window:GetLayerType()
    return self:_OnGetLayerType()
end

function Window:GetReturnKeyOperation()
   return self:_OnGetReturnKeyOperation()
end

------------------------- 下面是虚函数 ----------------------------
function Window:_OnGetName()
    return "NamelessWindow"
end

function Window:_OnGetLayerType()
    return Enum.LayerType.UI
end

function Window:_OnGetReturnKeyOperation()
    return Enum.ReturnKeyOperation.Back
end
---------------------------------------------------------------------

return Window